# Generated by Django 4.2.29 on 2026-03-14 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educhat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='chat',
            name='subject',
            field=models.CharField(choices=[('maths', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('geographie', 'Géographie'), ('histoire', 'Histoire'), ('francais', 'Français'), ('anglais', 'Anglais'), ('philosophie', 'Philosophie')], default='maths', max_length=20),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='educhat.chat'),
        ),
    ]
